name: Unit tests
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: npm ci
      - name: Build the library
        run: npm run build
      - name: Test the library
        run: npm run test
